name: quadruped_pympc_env
channels:
- conda-forge
- robostack-staging
dependencies:
- pip
- python
- casadi==3.6.5
- numpy
- matplotlib
- jaxlib
- jax
- meshcat-python 
- scipy 
- pinocchio
- adam-robotics[all]
- compilers 
- cmake 
- pkg-config 
- make 
- tqdm
- gymnasium
- pip:
  - mujoco
  - readchar
  - liecasadi

