name: quadruped_pympc_env
channels:
- conda-forge
- robostack-staging
dependencies:
- python=3.11.8
- casadi
- numpy
- matplotlib
- jaxlib
- jax
- pinocchio
- meshcat-python 
- scipy 
- ros-noetic-desktop
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- catkin_tools 
- rosdep
- pip:
  - mujoco

