name: quadruped_pympc_env
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- python
- casadi
- numpy
- matplotlib
- jaxlib=*=*cuda*
- jax
- cuda-nvcc 
- pinocchio  
- scipy 
- ros-noetic-desktop
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- catkin_tools 
- rosdep
- pip:
  - mujoco

